import turtle

pantalla=turtle.Screen()
pantalla.setup(425,425)
pantalla.screensize(400,400)
pantalla.setworldcoordinates(-400,-400,400,400)

tortuga=turtle.Turtle()

lado=int(input("Introduce el lado del cuadrado: "))

tortuga.width(1)
tortuga.penup()
tortuga.goto(-lado,0)
tortuga.setheading(0)
tortuga.pendown()
tortuga.forward(2*lado)
tortuga.penup()
tortuga.goto(0,-lado)
tortuga.setheading(90)
tortuga.pendown()
tortuga.forward(2*lado)
tortuga.penup()
tortuga.goto(0,-lado/2)
tortuga.pendown()
tortuga.width(2)
tortuga.setheading(0)
tortuga.circle(lado/2)
tortuga.penup()
tortuga.goto(lado/2,-lado/2)
tortuga.setheading(90)
tortuga.pendown()
tortuga.forward(lado)
tortuga.setheading(180)
tortuga.forward(lado)
tortuga.setheading(270)
tortuga.forward(lado)
tortuga.setheading(0)
tortuga.forward(lado)
pantalla.exitonclick()
